jobs:
  build:
    if: '!contains(github.event.head_commit.message, ''ci skip'') && (!contains(github.event_name,
      ''pull_request'') || (contains(github.event_name, ''pull_request'') && github.event.pull_request.head.repo.full_name
      != github.repository))'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: 'Checkout: Code'
      uses: actions/checkout@v2
    - continue-on-error: true
      if: contains(github.event_name, 'pull_request')
      name: 'Checkout: Code (PR)'
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - continue-on-error: true
      name: 'Setup: Java'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: 'Cache: Gradle'
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.*')
          }}
        path: '~/.gradle

          .gradle

          '
    - continue-on-error: true
      name: 'Build: Project with make'
      run: make clean all
    - continue-on-error: true
      if: always()
      name: 'Build: List dist files'
      run: find dist -type f -maxdepth 2
    - continue-on-error: true
      if: always()
      name: 'Artifacts: All'
      uses: actions/upload-artifact@v2.2.1
      with:
        name: all
        path: dist
        retention-days: 5
    - continue-on-error: true
      name: 'Artifacts: Android APK'
      uses: actions/upload-artifact@v2.2.1
      with:
        name: android-apk
        path: 'dist/*.apk

          '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___build-android-project.yml
